---
ID: "f10f13a7-8405-471a-9a29-dd67c148170f"
Parent: "2e92bbd6-afc9-4794-9cd8-0e948417dbd1"
Template: "2e92bbd6-afc9-4794-9cd8-0e948417dbd1"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Banner/_VideoHero/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180517T185641Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
