---
ID: "4b623c00-8767-4b63-b97e-b2522dc57406"
Parent: "2701a785-3b14-491a-b649-69774b42ec8c"
Template: "2701a785-3b14-491a-b649-69774b42ec8c"
Path: /sitecore/templates/SEIUMB/Feature/Rakuten/_ExclusiveOfferCarousel/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201117T230813Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af798eb1-4166-41e6-b4b8-08f5e3e8df47"
      Hint: Headline
      Value: Hot Deals for Members
