---
ID: "aed73295-f934-47a5-b767-fbbc2adfeaee"
Parent: "6f05cb47-acd7-4888-8bb7-1824f19af43a"
Template: "6f05cb47-acd7-4888-8bb7-1824f19af43a"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Contest/_ContestItem/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200120T183703Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
