---
ID: "9932fb8f-ed30-4b13-8a26-0c8875ba8cfa"
Parent: "ee59e60c-4880-4f20-9788-bc6bd90ce130"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_NewsletterStep/Newsletter Step Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190312T151316Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
