---
ID: "9f64d9c4-49a7-4561-ac45-4f47e6eaa615"
Parent: "cf79d433-b249-42e4-959f-cfa33ac6556a"
Template: "cf79d433-b249-42e4-959f-cfa33ac6556a"
Path: /sitecore/templates/SEIUMB/Feature/GeneralContent/_Head/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171116T215221Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
