---
ID: "c8ac0379-928e-439f-8fa8-4ddb3ba4c6c7"
Parent: "094ed756-0cab-40b2-9478-fd796657cc7e"
Template: "094ed756-0cab-40b2-9478-fd796657cc7e"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Topic Listing/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201008T040521Z
