---
ID: "5b510ebd-083a-4f46-bfb9-526acfcabd17"
Parent: "920209c3-d1e9-4da1-81a0-0f138122f0b9"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_ProductPageView/Configuration/Product Page View Code
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:/sitecore/content/NEAMB/Global/Product Codes/*[@@templatename='Product Code']"
- ID: "21828437-ea4b-40a1-8c61-4ce60ea41db6"
  Hint: Validate Button
  Type: tree list
  Value: "{59D4EE10-627C-4FD3-A964-61A88B092CBC}"
- ID: "337e20e1-999a-4eea-85ad-b58a03ae75cc"
  Hint: Quick Action Bar
  Type: tree list
  Value: "{59D4EE10-627C-4FD3-A964-61A88B092CBC}"
- ID: "53c432c4-7122-4e2d-8296-db4184fd1735"
  Hint: Workflow
  Type: tree list
  Value: "{59D4EE10-627C-4FD3-A964-61A88B092CBC}"
- ID: "9c903e29-650d-4af2-b9bd-526d5c14a1a5"
  Hint: Validator Bar
  Type: tree list
  Value: "{59D4EE10-627C-4FD3-A964-61A88B092CBC}"
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droplink
Languages:
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: Product code to send to Oracle DB on page view
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221017T144428Z
