---
ID: "7b55137d-188a-4509-8ecc-16b25e5d3416"
Parent: "dc52d1b9-15dd-4f88-b7a2-83138a12db0d"
Template: "dc52d1b9-15dd-4f88-b7a2-83138a12db0d"
Path: /sitecore/templates/SEIUMB/Feature/GeneralContent/_ChatSnippet/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210316T203005Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
