---
ID: "fa41a183-332f-4303-a47f-d9ca5f50e2b3"
Parent: "93d819e3-5aa4-49f0-a392-d2e80659602e"
Template: "93d819e3-5aa4-49f0-a392-d2e80659602e"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Cards/_TwoColumCarousel/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "10186210-f257-4806-b344-c2d5e839d6c1"
      Hint: Header
      Value: Insert your headline here
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180511T174020Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
