---
ID: "39ce7499-dec0-4041-9cd9-a4e620ef776c"
Parent: "7521907d-bb63-48ec-b661-74e52df80a80"
Template: "7521907d-bb63-48ec-b661-74e52df80a80"
Path: /sitecore/templates/SEIUMB/Feature/Product/_Listing/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T180721Z
    - ID: "4e6a5d79-f1dd-40b5-9adf-dd4b4b6afac3"
      Hint: Headline
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "89b0fb04-597a-48e6-a8cf-5037d3cada85"
      Hint: MoreLink
      Value: More
    - ID: "9b30869f-186b-43a0-82c6-8340bea71fbc"
      Hint: Image
      Value: |
        <image mediapath="/NEAMBC/SEIUMB/Images/Dummy Images/500x350" alt="" width="" height="" hspace="" vspace="" showineditor="" usethumbnail="" src="~/media/NEAMBC/SEIUMB/Images/Dummy Images/500x350" mediaid="{8552298C-2BC7-412D-931C-A377A6C7AB83}" />
    - ID: "a50409d3-c6b3-4de3-b7ad-3d6acdac88cc"
      Hint: Summary
      Value: Insert your summary here
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171220T223904Z
    - ID: "4e6a5d79-f1dd-40b5-9adf-dd4b4b6afac3"
      Hint: Headline
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "89b0fb04-597a-48e6-a8cf-5037d3cada85"
      Hint: MoreLink
      Value: Más
    - ID: "9b30869f-186b-43a0-82c6-8340bea71fbc"
      Hint: Image
      Value: |
        <image mediaid="{8552298C-2BC7-412D-931C-A377A6C7AB83}" />
    - ID: "a50409d3-c6b3-4de3-b7ad-3d6acdac88cc"
      Hint: Summary
      Value: Insert your summary here
