---
ID: "7e3f43fe-6ab2-4a60-b9a1-2984ec963654"
Parent: "ee80d227-3517-4170-913e-ff48a15d3efa"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/content/NEAMBC/Home/UITest/Products
DB: master
SharedFields:
- ID: "74484bdf-7c86-463c-b49f-7b73b9afc965"
  Hint: __Publishing groups
  Type: checklist
  Value: "{8E080626-DDC3-4EF4-A1D1-F0BE4A200254}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201028T174223Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mdavalos
