---
ID: "6ad5b682-f94a-408b-99e5-9ec0a17bea1c"
Parent: "8752b292-ed92-484f-8a88-d6ead7f79e45"
Template: "8752b292-ed92-484f-8a88-d6ead7f79e45"
Path: /sitecore/templates/SEIUMB/Foundation/Indexing/_IndexedItem/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T204356Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "88119b5b-9b08-417e-83e3-6451589abf30"
      Hint: IncludeInSearchResults
      Type: Checkbox
      Value: 1
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171227T204330Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "88119b5b-9b08-417e-83e3-6451589abf30"
      Hint: IncludeInSearchResults
      Type: Checkbox
      Value: 1
