---
ID: "03c76daf-6fe8-46ab-9d43-bfb030bd3a76"
Parent: "679d2691-a0d6-4684-b78f-6988d95a1d14"
Template: "679d2691-a0d6-4684-b78f-6988d95a1d14"
Path: /sitecore/templates/SEIUMB/Project/Web/Content Types/Division Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200608T213537Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
