---
ID: "b48698b6-9a35-40a3-94f0-b79c4b78e0ef"
Parent: "a6db2d17-7a1b-46c0-90f7-67d78f4d1e32"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_RetirementProduct/Product Info
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221004T160931Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
