//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neambc.Neamb.Foundation.MBCData.EnrollmentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment", ConfigurationName="EnrollmentService.EnrollmentSoap")]
    public interface EnrollmentSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/SiteGUID", ReplyAction="*")]
        System.Guid SiteGUID();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/SiteGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> SiteGUIDAsync();
        
        // CODEGEN: Generating message contract since element name ExportCheckSumResult from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/ExportCheckSum", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponse ExportCheckSum(Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/ExportCheckSum", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponse> ExportCheckSumAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/CheckUser", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponse CheckUser(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/CheckUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponse> CheckUserAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest request);
        
        // CODEGEN: Generating message contract since element name pin from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/CheckEmployeePIN", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponse CheckEmployeePIN(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/CheckEmployeePIN", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponse> CheckEmployeePINAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/LoginGUID", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponse LoginGUID(Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/LoginGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponse> LoginGUIDAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/GetLoginGUID", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponse GetLoginGUID(Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/GetLoginGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponse> GetLoginGUIDAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/PortfolioAsOfDate", ReplyAction="*")]
        System.DateTime PortfolioAsOfDate(System.Guid portfolioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/PortfolioAsOfDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> PortfolioAsOfDateAsync(System.Guid portfolioID);
        
        // CODEGEN: Generating message contract since element name user from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/Upload", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponse Upload(Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/Upload", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponse> UploadAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://benefits-selection.com/qx/enrollment is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/Query", ReplyAction="*")]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponse Query(Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://benefits-selection.com/qx/enrollment/Query", ReplyAction="*")]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponse> QueryAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportCheckSumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportCheckSum", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequestBody Body;
        
        public ExportCheckSumRequest() {
        }
        
        public ExportCheckSumRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class ExportCheckSumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid exportID;
        
        public ExportCheckSumRequestBody() {
        }
        
        public ExportCheckSumRequestBody(System.Guid exportID) {
            this.exportID = exportID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportCheckSumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportCheckSumResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponseBody Body;
        
        public ExportCheckSumResponse() {
        }
        
        public ExportCheckSumResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class ExportCheckSumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExportCheckSumResult;
        
        public ExportCheckSumResponseBody() {
        }
        
        public ExportCheckSumResponseBody(string ExportCheckSumResult) {
            this.ExportCheckSumResult = ExportCheckSumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUser", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequestBody Body;
        
        public CheckUserRequest() {
        }
        
        public CheckUserRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class CheckUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        public CheckUserRequestBody() {
        }
        
        public CheckUserRequestBody(string user, string passwd) {
            this.user = user;
            this.passwd = passwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponseBody Body;
        
        public CheckUserResponse() {
        }
        
        public CheckUserResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class CheckUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserResult;
        
        public CheckUserResponseBody() {
        }
        
        public CheckUserResponseBody(bool CheckUserResult) {
            this.CheckUserResult = CheckUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEmployeePINRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEmployeePIN", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequestBody Body;
        
        public CheckEmployeePINRequest() {
        }
        
        public CheckEmployeePINRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class CheckEmployeePINRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid portfolioID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid employeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pin;
        
        public CheckEmployeePINRequestBody() {
        }
        
        public CheckEmployeePINRequestBody(System.Guid portfolioID, System.Guid employeeID, string pin) {
            this.portfolioID = portfolioID;
            this.employeeID = employeeID;
            this.pin = pin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckEmployeePINResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckEmployeePINResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponseBody Body;
        
        public CheckEmployeePINResponse() {
        }
        
        public CheckEmployeePINResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class CheckEmployeePINResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckEmployeePINResult;
        
        public CheckEmployeePINResponseBody() {
        }
        
        public CheckEmployeePINResponseBody(bool CheckEmployeePINResult) {
            this.CheckEmployeePINResult = CheckEmployeePINResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginGUID", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequestBody Body;
        
        public LoginGUIDRequest() {
        }
        
        public LoginGUIDRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class LoginGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid uniqueID;
        
        public LoginGUIDRequestBody() {
        }
        
        public LoginGUIDRequestBody(string user, string passwd, System.Guid uniqueID) {
            this.user = user;
            this.passwd = passwd;
            this.uniqueID = uniqueID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginGUIDResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponseBody Body;
        
        public LoginGUIDResponse() {
        }
        
        public LoginGUIDResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class LoginGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid LoginGUIDResult;
        
        public LoginGUIDResponseBody() {
        }
        
        public LoginGUIDResponseBody(System.Guid LoginGUIDResult) {
            this.LoginGUIDResult = LoginGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginGUID", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequestBody Body;
        
        public GetLoginGUIDRequest() {
        }
        
        public GetLoginGUIDRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class GetLoginGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid portfolioID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Guid uniqueID;
        
        public GetLoginGUIDRequestBody() {
        }
        
        public GetLoginGUIDRequestBody(string user, string passwd, System.Guid portfolioID, System.Guid uniqueID) {
            this.user = user;
            this.passwd = passwd;
            this.portfolioID = portfolioID;
            this.uniqueID = uniqueID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginGUIDResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponseBody Body;
        
        public GetLoginGUIDResponse() {
        }
        
        public GetLoginGUIDResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class GetLoginGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid GetLoginGUIDResult;
        
        public GetLoginGUIDResponseBody() {
        }
        
        public GetLoginGUIDResponseBody(System.Guid GetLoginGUIDResult) {
            this.GetLoginGUIDResult = GetLoginGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Upload", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequestBody Body;
        
        public UploadRequest() {
        }
        
        public UploadRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class UploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data;
        
        public UploadRequestBody() {
        }
        
        public UploadRequestBody(string user, string passwd, string data) {
            this.user = user;
            this.passwd = passwd;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponseBody Body;
        
        public UploadResponse() {
        }
        
        public UploadResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class UploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadResult;
        
        public UploadResponseBody() {
        }
        
        public UploadResponseBody(string UploadResult) {
            this.UploadResult = UploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Query", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequestBody Body;
        
        public QueryRequest() {
        }
        
        public QueryRequest(Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class QueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data;
        
        public QueryRequestBody() {
        }
        
        public QueryRequestBody(string user, string passwd, string data) {
            this.user = user;
            this.passwd = passwd;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryResponse", Namespace="https://benefits-selection.com/qx/enrollment", Order=0)]
        public Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponseBody Body;
        
        public QueryResponse() {
        }
        
        public QueryResponse(Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://benefits-selection.com/qx/enrollment")]
    public partial class QueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryResult;
        
        public QueryResponseBody() {
        }
        
        public QueryResponseBody(string QueryResult) {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnrollmentSoapChannel : Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnrollmentSoapClient : System.ServiceModel.ClientBase<Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap>, Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap {
        
        public EnrollmentSoapClient() {
        }
        
        public EnrollmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnrollmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid SiteGUID() {
            return base.Channel.SiteGUID();
        }
        
        public System.Threading.Tasks.Task<System.Guid> SiteGUIDAsync() {
            return base.Channel.SiteGUIDAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.ExportCheckSum(Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest request) {
            return base.Channel.ExportCheckSum(request);
        }
        
        public string ExportCheckSum(System.Guid exportID) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequestBody();
            inValue.Body.exportID = exportID;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).ExportCheckSum(inValue);
            return retVal.Body.ExportCheckSumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.ExportCheckSumAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest request) {
            return base.Channel.ExportCheckSumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumResponse> ExportCheckSumAsync(System.Guid exportID) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.ExportCheckSumRequestBody();
            inValue.Body.exportID = exportID;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).ExportCheckSumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.CheckUser(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest request) {
            return base.Channel.CheckUser(request);
        }
        
        public bool CheckUser(string user, string passwd) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).CheckUser(inValue);
            return retVal.Body.CheckUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.CheckUserAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest request) {
            return base.Channel.CheckUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserResponse> CheckUserAsync(string user, string passwd) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).CheckUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.CheckEmployeePIN(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest request) {
            return base.Channel.CheckEmployeePIN(request);
        }
        
        public bool CheckEmployeePIN(System.Guid portfolioID, System.Guid employeeID, string pin) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequestBody();
            inValue.Body.portfolioID = portfolioID;
            inValue.Body.employeeID = employeeID;
            inValue.Body.pin = pin;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).CheckEmployeePIN(inValue);
            return retVal.Body.CheckEmployeePINResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.CheckEmployeePINAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest request) {
            return base.Channel.CheckEmployeePINAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINResponse> CheckEmployeePINAsync(System.Guid portfolioID, System.Guid employeeID, string pin) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.CheckEmployeePINRequestBody();
            inValue.Body.portfolioID = portfolioID;
            inValue.Body.employeeID = employeeID;
            inValue.Body.pin = pin;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).CheckEmployeePINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.LoginGUID(Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest request) {
            return base.Channel.LoginGUID(request);
        }
        
        public System.Guid LoginGUID(string user, string passwd, System.Guid uniqueID) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.uniqueID = uniqueID;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).LoginGUID(inValue);
            return retVal.Body.LoginGUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.LoginGUIDAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest request) {
            return base.Channel.LoginGUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDResponse> LoginGUIDAsync(string user, string passwd, System.Guid uniqueID) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.LoginGUIDRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.uniqueID = uniqueID;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).LoginGUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.GetLoginGUID(Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest request) {
            return base.Channel.GetLoginGUID(request);
        }
        
        public System.Guid GetLoginGUID(string user, string passwd, System.Guid portfolioID, System.Guid uniqueID) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.portfolioID = portfolioID;
            inValue.Body.uniqueID = uniqueID;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).GetLoginGUID(inValue);
            return retVal.Body.GetLoginGUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.GetLoginGUIDAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest request) {
            return base.Channel.GetLoginGUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDResponse> GetLoginGUIDAsync(string user, string passwd, System.Guid portfolioID, System.Guid uniqueID) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.GetLoginGUIDRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.portfolioID = portfolioID;
            inValue.Body.uniqueID = uniqueID;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).GetLoginGUIDAsync(inValue);
        }
        
        public System.DateTime PortfolioAsOfDate(System.Guid portfolioID) {
            return base.Channel.PortfolioAsOfDate(portfolioID);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> PortfolioAsOfDateAsync(System.Guid portfolioID) {
            return base.Channel.PortfolioAsOfDateAsync(portfolioID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.Upload(Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public string Upload(string user, string passwd, string data) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.data = data;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).Upload(inValue);
            return retVal.Body.UploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.UploadAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadResponse> UploadAsync(string user, string passwd, string data) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.UploadRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.data = data;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).UploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponse Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.Query(Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public string Query(string user, string passwd, string data) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.data = data;
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponse retVal = ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).Query(inValue);
            return retVal.Body.QueryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponse> Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap.QueryAsync(Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryResponse> QueryAsync(string user, string passwd, string data) {
            Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest inValue = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequest();
            inValue.Body = new Neambc.Neamb.Foundation.MBCData.EnrollmentService.QueryRequestBody();
            inValue.Body.user = user;
            inValue.Body.passwd = passwd;
            inValue.Body.data = data;
            return ((Neambc.Neamb.Foundation.MBCData.EnrollmentService.EnrollmentSoap)(this)).QueryAsync(inValue);
        }
    }
}
