---
ID: "7183e146-068e-4ea1-aa9a-cf4620de567b"
Parent: "8c963cf0-8e65-481f-b3f1-306c43e75720"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/NEAMB/Feature/Neamb_Product/Product CTAs C034
DB: master
SharedFields:
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductDetail
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Neambc.Neamb.Feature.Product.Controllers.ProductController,Neambc.Neamb.Feature.Product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180503T194449Z
