---
ID: "fbddc884-c227-4970-a5f6-a04e5b126cbe"
Parent: "c23718eb-13d3-417a-80eb-a8942be2b236"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_SpecialOffer/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180627T200615Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
