---
ID: "9a543a61-1d93-4275-ba9d-c1dc174eec3b"
Parent: "4aac4ff2-46bc-4e2d-b1c4-b1dcff26e6bf"
Template: "4aac4ff2-46bc-4e2d-b1c4-b1dcff26e6bf"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Session Variable/__Standard Values
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{599EAC95-E90F-4493-A258-02F44C864E74}"
Languages:
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190409T191135Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
