---
ID: "79e39f82-0239-4062-8449-08adcadcac70"
Parent: "d613828e-0662-45f9-9a35-d1c6c47271e8"
Template: "d613828e-0662-45f9-9a35-d1c6c47271e8"
Path: /sitecore/templates/SEIUMB/Project/Web/Page Types/Error Page/__Standard Values
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{B23AAF23-9706-4858-855A-15CC3CC813FF}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{66FE58B2-6BC6-45D1-A4FE-8FB3E69659AE}">
        <p
          uid="{32B3AE17-390B-438F-ABC4-01BE04BD515E}"
          key="body"
          md="{3750AF4A-309C-404F-A9D4-B05B44343122}" />
        <r
          id="{ACDAE1DC-60AA-456A-9A16-6496E05307FD}"
          ph="header"
          uid="{127873A9-03AD-44EE-81D0-4CBFB4376EC8}" />
        <r
          ds="{320FB78C-3992-47D9-8820-98D5C6A58D2D}"
          id="{06B0A82F-D054-472D-8A71-05B10B8684E6}"
          ph="login"
          uid="{1449B440-0226-4B16-9B07-8E77C3843BC2}" />
        <r
          id="{C84D8A64-333A-4608-BA56-8E73DCA73D0E}"
          ph="language-selector"
          uid="{AE478752-5B52-45F7-8541-9E4D6777B587}" />
        <r
          id="{3212661B-20D7-45C0-A1C0-F42406936DF6}"
          ph="language-selector-mobile"
          uid="{DAF412F6-CAF6-4DDD-9124-6EB5C599961F}" />
        <r
          id="{07B57C87-E37A-49D1-9647-00DC83B69A1C}"
          ph="navbar-top"
          uid="{E73DED3D-9B39-4868-ACB9-235728ADEF18}" />
        <r
          id="{8225BD3A-468F-4859-8B88-D711BCF24A16}"
          ph="body"
          uid="{CA217C91-FF39-494C-B079-D35B82E0C013}" />
        <r
          id="{C46199B9-B82C-4626-A4AE-3E868946D5F2}"
          ph="navbar-bottom"
          uid="{683BAC05-DACD-4834-8B70-E873206F5AA7}" />
        <r
          ds="{46D06DD7-8928-43F3-AC91-64FFC27778DC}"
          id="{EF9080D5-D67C-4960-BC92-C996D4BA70EE}"
          ph="footer"
          uid="{85AE15EA-48A8-4535-A1A5-06BF45882103}" />
      </d>
    </r>
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{85AE15EA-48A8-4535-A1A5-06BF45882103}">
              <rls>
                <ruleset>
                  <rule
                    uid="{00000000-0000-0000-0000-000000000000}"
                    s:name="Default">
                    <conditions>
                      <condition
                        uid="BFC4D97366474258B5D6F440618B81FD"
                        s:id="{4888ABBB-F17D-4485-B14B-842413F88732}" />
                    </conditions>
                    <actions />
                  </rule>
                </ruleset>
              </rls>
            </r>
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171127T030348Z
    - ID: "25df7e83-4554-4b36-98d2-6359d8c7df59"
      Hint: Body
      Value: 
    - ID: "4e0ccd80-281f-4bbd-b288-63f810623c2c"
      Hint: Title
      Value: Error
    - ID: "595b93c5-514a-410c-95e2-c597e1189faf"
      Hint: ContinueButton
      Value: |
        <link text="Continue" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{72051F7F-87F7-4279-B455-5A7EACA902F5}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171227T205439Z
    - ID: "25df7e83-4554-4b36-98d2-6359d8c7df59"
      Hint: Body
      Value: |
        <p>There was an error submitting your form. Please try again later or <a href="~/link.aspx?_id=D4DA125753A742EDA53DF73040BE3B0A&amp;_z=z">contact us.</a></p>
    - ID: "4e0ccd80-281f-4bbd-b288-63f810623c2c"
      Hint: Title
      Value: Error
    - ID: "595b93c5-514a-410c-95e2-c597e1189faf"
      Hint: ContinueButton
      Value: |
        <link text="Continuar" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{72051F7F-87F7-4279-B455-5A7EACA902F5}" />
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
