---
ID: "af0214e7-bbfa-4325-bf82-84e5f99e01f2"
Parent: "d0942182-aa89-4f5b-a2c5-7d66e98cf581"
Template: "d0942182-aa89-4f5b-a2c5-7d66e98cf581"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Carousel Offer Cards/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210429T170548Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
