---
ID: "82e05ce0-68df-4172-ac54-f66a7fe785d4"
Parent: "1f0f2c33-902c-40c5-9f1c-7502a60df3d5"
Template: "1f0f2c33-902c-40c5-9f1c-7502a60df3d5"
Path: /sitecore/templates/SEIUMB/Feature/GeneralContent/_PageSettings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171207T160131Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
