---
ID: "0e1038f9-51e6-47e0-a38b-f009e0b15b77"
Parent: "668d8d54-dc74-475d-902f-611a1eed6371"
Template: "668d8d54-dc74-475d-902f-611a1eed6371"
Path: /sitecore/templates/NEAMB/Project/Web/Base Page Templates/_PageHeader/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180426T162628Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5ee361e9-bf9e-4d1f-8ce0-9403d6d7c838"
      Hint: Subheadline
      Value: 
    - ID: "883f4d18-7002-44ce-8feb-5a0e17661ece"
      Hint: Hero Image
      Value: 
