---
ID: "f6e18d0d-874d-44a1-a1dd-fdd9cbabbbd5"
Parent: "ad5d2b08-dc4f-4229-bea3-52a917c42251"
Template: "7f85b6d0-f533-45ac-b00b-ddd602ab6fcf"
Path: /sitecore/content/NEAMBC/Global/Categories/Topics/Products and Services
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 700
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T190234Z
    - ID: "6e092b84-f2ce-477a-af26-db4c0bf85ad0"
      Hint: Value
      Value: "General Info - Products and Services"
    - ID: "73494340-4626-4d41-a5e7-f0ec2664c0b0"
      Hint: ItemName
      Value: "General Info - Products and Services"
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180103T225355Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sfernandez
    - ID: "6e092b84-f2ce-477a-af26-db4c0bf85ad0"
      Hint: Value
      Value: "Información general - Productos y servicios"
    - ID: "73494340-4626-4d41-a5e7-f0ec2664c0b0"
      Hint: ItemName
      Value: "Información general - Productos y servicios"
