---
ID: "6d91fae1-20be-4d76-b347-acd006cd78e3"
Parent: "beb6b0c1-fd97-41d5-b7d8-054be69faa99"
Template: "beb6b0c1-fd97-41d5-b7d8-054be69faa99"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Rich Text Block/__Standard Values
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{599EAC95-E90F-4493-A258-02F44C864E74}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{599EAC95-E90F-4493-A258-02F44C864E74}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180726T203650Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
