---
ID: "437d1e5a-4d82-4c0a-89e1-e40cb2b7f098"
Parent: "3d72c5ce-6691-4e51-aefc-59d1c19cf688"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_ProductRedirect/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210413T201804Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
