---
ID: "766bd036-138f-4f74-b70f-525573e45cc3"
Parent: "40e9d39e-1f56-48a8-bb70-ca76353c5e21"
Template: "40e9d39e-1f56-48a8-bb70-ca76353c5e21"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Rakuten Category Item/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200722T185748Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
