---
ID: "341872aa-4a28-4183-b50c-970bef1deac6"
Parent: "699dab2a-06ae-40ed-a3d3-697a676813e4"
Template: "699dab2a-06ae-40ed-a3d3-697a676813e4"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Product Radio Button Option/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220928T181912Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
