---
ID: "7f638446-6000-4c80-a188-57f121daa27b"
Parent: "7fa30ad4-021c-4992-aa53-c2e225fe2c1a"
Template: "7fa30ad4-021c-4992-aa53-c2e225fe2c1a"
Path: /sitecore/templates/SEIUMB/Project/Web/Content Types/Site Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171110T233208Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
