---
ID: "1ee9ebe9-1e67-43be-b49d-9d583c2b2b7f"
Parent: "daf3ef5e-01d4-4fdd-a5b6-db0f92fdc131"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/NEAMB/Feature/Neamb_GeneralContent/_LightBox/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190212T204259Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
