---
ID: "464e4a4f-67af-4c5f-8174-15e349145606"
Parent: "38a6d46c-9ac3-404f-8c94-8461409f3426"
Template: "38a6d46c-9ac3-404f-8c94-8461409f3426"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Product Mapping Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220929T150109Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
