---
ID: "a3118db2-eb7d-4837-8e2d-78ef28173835"
Parent: "477e3654-94ad-41f9-94a8-dabbddb8df11"
Template: "477e3654-94ad-41f9-94a8-dabbddb8df11"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Half Background Tout Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210505T173355Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8c3564d4-1ba2-4c69-8c73-18d3e31baba6"
      Hint: Background Color
      Value: F5F4F1
