---
ID: "b264fceb-582e-478f-bf71-a6529b3a8884"
Parent: "2bfabcae-86da-48cf-a140-849c44b30574"
Template: "2bfabcae-86da-48cf-a140-849c44b30574"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Header Offer Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210419T172116Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
