//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neambc.Seiumb.Foundation.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/seiumb.seiumbHttpSoap11Endpoint/")]
        public string Neambc_Seiumb_Foundation_WebServices_org_neambc_elegibility_seiumb {
            get {
                return ((string)(this["Neambc_Seiumb_Foundation_WebServices_org_neambc_elegibility_seiumb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/aes256EncryptDecrypt.aes256EncryptDecryp" +
            "tHttpSoap11Endpoint/")]
        public string Neambc_Seiumb_Foundation_WebServices_org_neambc_encryptafinium_aes256EncryptDecrypt {
            get {
                return ((string)(this["Neambc_Seiumb_Foundation_WebServices_org_neambc_encryptafinium_aes256EncryptDecry" +
                    "pt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.122.1:8080/axis2/services/AccountManagement.AccountManagementHttpS" +
            "oap11Endpoint/")]
        public string Neambc_Seiumb_Foundation_WebServices_org_neambc_acctmgt_AccountManagement {
            get {
                return ((string)(this["Neambc_Seiumb_Foundation_WebServices_org_neambc_acctmgt_AccountManagement"]));
            }
        }
    }
}
