---
ID: "d7125b4c-e4aa-4c56-a7e2-a5bc2369b88b"
Parent: "8a44d99d-25f7-459e-8983-728992188910"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_ProductCTAs/Configuration/Product Code
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: "query:/sitecore/content/NEAMB/Global/Product Codes/*[@@templatename='Product Code']"
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droplink
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1000
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220106T182556Z
