---
ID: "3432881d-01c5-4d40-9f8a-9868b049c926"
Parent: "8a44d99d-25f7-459e-8983-728992188910"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/NEAMB/Feature/Neamb_Product/_ProductCTAs/Configuration/Product Contact Details
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Rich Text
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220824T154328Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
