---
ID: "b96733b7-5086-4af4-8686-ee2bf58cc4a9"
Parent: "ef8f4901-5340-4d9d-b991-88fe0521a5e4"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/SEIUMB/Feature/Product/_ProductLite/General/ProductSubHeadline
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Rich Text
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 237
Languages:
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: "Product Sub-headline"
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: "Use to define this product sub-headline"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Subheadline
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171120T172339Z
