---
ID: "c0e98d13-736c-4dd3-bd9e-ac38939234ef"
Parent: "807c333a-322c-4e23-9607-e4e2c6806b13"
Template: "807c333a-322c-4e23-9607-e4e2c6806b13"
Path: /sitecore/templates/SEIUMB/Feature/GeneralContent/_SmallAccordion/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201203T215333Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "be259f86-a61f-4e00-9311-c3b3592e33c9"
      Hint: Header
      Value: FAQs
