---
ID: "2a968629-7164-4f6d-ade0-a89b5b20ef9a"
Parent: "6fb29da4-e1ce-47b9-83b5-f2495a3bf342"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/NEAMB/Foundation/Neamb_Rakuten/_RakutenCalculated/Rakuten Calculated Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200814T024918Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\pbustamante
