using System.ComponentModel;

namespace Neambc.Neamb.Foundation.MBCData.Enums
{
    public enum Token
    {
        [Description("")]
        None,
        [Description("cellcode")]
        cellcode,
        [Description("campcode")]
        campcode,
        [Description("medium")]
        medium,
        [Description("term")]
        term,
        [Description("FirstName")]
        FirstName,
        [Description("LastName")]
        LastName,
        [Description("Phone")]
        Phone,
        [Description("Email")]
        Email,
        [Description("StateCode")]
        StateCode,
        [Description("IcePoints")]
        IcePoints,
        [Description("StateNames")]
        StateNames,
        [Description("IceTravelDollars")]
        IceTravelDollars,
        [Description("ReturnUrl")]
        ReturnUrl,
        [Description("SeminarAddress")]
        SeminarAddress,
        [Description("SeminarDate")]
        SeminarDate,
        [Description("SeminarTime")]
        SeminarTime,
        [Description("SeminarName")]
        SeminarName,
        [Description("SeaName")]
        SeaName,
        [Description("LeaName")]
        LeaName,
        [Description("SeminarLocation1")]
        SeminarLocation1,
        [Description("SeminarLocation2")]
        SeminarLocation2,
        [Description("SeminarCityStateZipCode")]
        SeminarCityStateZipCode,
        [Description("NotYou")]
        NotYou,
        [Description("PresenterName")]
        PresenterName,
        [Description("FirstNameExclamation")]
        FirstNameExclamation,
        [Description("mdsid_clear")]
        mdsid_clear,
        [Description("mdsid_clear_int")]
        mdsid_clear_int,
        [Description("rakuten_signup")]
        rakuten_signup,
        [Description("mercer")]
        Mercer,
        [Description("afinium")]
        Afinium,
        [Description("OmniSoctUrl")]
        OmniSoctUrl,
        [Description("OmniExpirationDate")]
        OmniExpirationDate,
        [Description("NCESID")]
        NcesId
    }
}