---
ID: "8d3e534e-9660-4f9e-a5e7-cab81a146283"
Parent: "1bdfa5b4-51dc-4922-a510-f2843590a4ae"
Template: "1bdfa5b4-51dc-4922-a510-f2843590a4ae"
Path: /sitecore/templates/SEIUMB/Project/Web/Content Types/SEIUMB Local Code/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200608T205523Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
