//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Neambc.Neamb.Foundation.MBCData.org.neambc.neamb.compintrolife {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="compIntroLifeSoap11Binding", Namespace="http://webservices.neamb")]
    public partial class compIntroLife : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback compIntroCheckOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public compIntroLife() {
            this.Url = global::Neambc.Neamb.Foundation.MBCData.Properties.Settings.Default.Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_compintrolife_compIntroLife;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event compIntroCheckCompletedEventHandler compIntroCheckCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:compIntroCheck", RequestNamespace="http://webservices.neamb", ResponseNamespace="http://webservices.neamb", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public compIntroObject compIntroCheck([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mdsid, int months, [System.Xml.Serialization.XmlIgnoreAttribute()] bool monthsSpecified) {
            object[] results = this.Invoke("compIntroCheck", new object[] {
                        mdsid,
                        months,
                        monthsSpecified});
            return ((compIntroObject)(results[0]));
        }
        
        /// <remarks/>
        public void compIntroCheckAsync(string mdsid, int months, bool monthsSpecified) {
            this.compIntroCheckAsync(mdsid, months, monthsSpecified, null);
        }
        
        /// <remarks/>
        public void compIntroCheckAsync(string mdsid, int months, bool monthsSpecified, object userState) {
            if ((this.compIntroCheckOperationCompleted == null)) {
                this.compIntroCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompIntroCheckOperationCompleted);
            }
            this.InvokeAsync("compIntroCheck", new object[] {
                        mdsid,
                        months,
                        monthsSpecified}, this.compIntroCheckOperationCompleted, userState);
        }
        
        private void OncompIntroCheckOperationCompleted(object arg) {
            if ((this.compIntroCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.compIntroCheckCompleted(this, new compIntroCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.neamb/xsd")]
    public partial class compIntroObject {
        
        private string compLifeField;
        
        private string introLifeField;
        
        private string signDateField;
        
        private string signDateCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string compLife {
            get {
                return this.compLifeField;
            }
            set {
                this.compLifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string introLife {
            get {
                return this.introLifeField;
            }
            set {
                this.introLifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signDate {
            get {
                return this.signDateField;
            }
            set {
                this.signDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signDateCode {
            get {
                return this.signDateCodeField;
            }
            set {
                this.signDateCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void compIntroCheckCompletedEventHandler(object sender, compIntroCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class compIntroCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal compIntroCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public compIntroObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((compIntroObject)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591