---
ID: "f54ec845-a68c-44b8-89a8-0d2854bdea1f"
Parent: "9e28ea74-cab3-4df8-b3cf-6a87ecaeffe7"
Template: "9e28ea74-cab3-4df8-b3cf-6a87ecaeffe7"
Path: /sitecore/templates/NEAMB/Project/Web/Content Type/Rakuten Reward/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200805T200852Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
