---
ID: "b953c42a-8718-4d7b-87af-cb93ac85fb39"
Parent: "249e4e0b-a07f-4321-96ed-9434c0046fd5"
Template: "249e4e0b-a07f-4321-96ed-9434c0046fd5"
Path: /sitecore/templates/NEAMB/Project/Web/Base Page Templates/_GenreAttribute/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180729T072213Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
