---
ID: "118615cf-4a9b-4c41-8af7-d638808159f6"
Parent: "3dcc040c-823f-4b96-bb76-2cd6a8d407f2"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/NEAMB/Feature/Neamb_Account/Settings and Subscriptions FA005
DB: master
SharedFields:
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: SettingsAndSubs
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Neambc.Neamb.Feature.Account.Controllers.SettingsAndSubsController, Neambc.Neamb.Feature.Account
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180613T225933Z
