---
ID: "00ac1c6a-2f2f-4160-9769-49c2e9fc3daa"
Parent: "7f85b6d0-f533-45ac-b00b-ddd602ab6fcf"
Template: "7f85b6d0-f533-45ac-b00b-ddd602ab6fcf"
Path: /sitecore/templates/SEIUMB/Project/Web/Content Types/Name Value Item/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171114T192803Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
