//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neambc.Neamb.Foundation.MBCData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/Efulfillment.EfulfillmentHttpSoap11Endpo" +
            "int/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_efulfillment_Efulfillment {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_efulfillment_Efulfillment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/PdfFactory.PdfFactoryHttpSoap11Endpoint/" +
            "")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_pdffactory_PdfFactory {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_pdffactory_PdfFactory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/productRules.productRulesHttpSoap11Endpo" +
            "int/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_productrules_productRules {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_productrules_productRules"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/compIntroLife.compIntroLifeHttpSoap11End" +
            "point/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_compintrolife_compIntroLife {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_compintrolife_compIntroLife"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.15.187:8080/axis2/services/aes256EncryptDecrypt.aes256EncryptDecryp" +
            "tHttpSoap11Endpoint/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_encryptmercer_aes256EncryptDecrypt {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_encryptmercer_aes256EncryptDecry" +
                    "pt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.122.1:8080/axis2/services/iceapis.iceapisHttpSoap11Endpoint/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_iceservice_iceapis {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_iceservice_iceapis"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.122.1:8080/axis2/services/memberdataversion2.memberdataversion2Htt" +
            "pSoap11Endpoint/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_memberdata_memberdataversion2 {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_memberdata_memberdataversion2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.122.1:8080/axis2/services/AccountManagement.AccountManagementHttpS" +
            "oap11Endpoint/")]
        public string Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_accountmng_AccountManagement {
            get {
                return ((string)(this["Neambc_Neamb_Foundation_MBCData_org_neambc_neamb_accountmng_AccountManagement"]));
            }
        }
    }
}
